steps:
  - id: "Store the Microservice URLs to the container volume mount"
    name: gcr.io/cloud-builders/gcloud
    entrypoint: /bin/bash
    args:
    - -c
    - |
      customer_service_url=$(gcloud run services describe gcp-training-customer-service --platform=managed --region=europe-west1 | grep https://gcp-training-customer-service)
      account_service_url=$(gcloud run services describe gcp-training-account-service --platform=managed --region=europe-west1 | grep https://gcp-training-account-service)
      cashier_service_url=$(gcloud run services describe gcp-training-cashier-service --platform=managed --region=europe-west1 | grep https://gcp-training-cashier-service)
      transaction_service_url=$(gcloud run services describe gcp-training-transaction-service --platform=managed --region=europe-west1 | grep https://gcp-training-transaction-service)
      balance_service_url=$(gcloud run services describe gcp-training-balance-service --platform=managed --region=europe-west1 | grep https://gcp-training-balance-service)
      
      echo ${customer_service_url} >> /workspace/customer_url.txt
      echo ${account_service_url} >> /workspace/account_url.txt
      echo ${cashier_service_url} >> /workspace/cashier_url.txt
      echo ${transaction_service_url} >> /workspace/transaction_url.txt
      echo ${balance_service_url} >> /workspace/balance_url.txt
      
  - id: "Execute Smoke Test"
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: bash
    args:
    - -c
    - |
      docker pull ${_CONTAINER_HOSTNAME}/$PROJECT_ID/${_SERVICE_NAME}:latest || exit 0
      docker run --rm --name test-container eu.gcr.io/asr-gcp-training/gcp-training-microservices-smoke-tests make tests -e CUSTOMER_SERVICE_URL=$(cat /workspace/customer_url.txt) -e ACCOUNT_SERVICE_URL=$(cat /workspace/account_url.txt) -e CASHIER_SERVICE_URL=$(cat /workspace/cashier_url.txt) -e TRANSACTION_SERVICE_URL=$(cat /workspace/transaction_url.txt) -e BALANCE_SERVICE_URL=$(cat /workspace/balance_url.txt)

substitutions:
  _CONTAINER_HOSTNAME: eu.gcr.io
  _SERVICE_NAME: gcp-training-microservices-smoke-tests
